music-app/urls.py
from django.contrib import admin
from django.conf.urls import url,include

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^music/',include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from .import views

app_name='music'

urlpatterns=[
	url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),
	url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite,name='favorite'),
	url(r'^$',views.index,name='index'),
]  

music/models.py
from django.db import models



class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title=models.CharField(max_length=500)
	genre=models.CharField(max_length=100)
	album_logo=models.CharField(max_length=1000)

	def __str__(self):
		return self.album_title + '-' + self.artist

class Song(models.Model):
	album=models.ForeignKey(Album,on_delete=models.CASCADE)
	file_type=models.CharField(max_length=10)
	song_title=models.CharField(max_length=50)
	is_favorite=models.BooleanField(default=False)
	

	def __str__(self):
		return self.song_title

music/views.py
from django.shortcuts import render,het_object_404
from django.http import HttpResponse
from .models import Album


def index(request):
	all_albums=Album.objects.all()
	# html=''
	# for album in all_albums:
	# 	url='/music/'+ str(album.id)+ '/'
	# 	html+='<a href="' + url + '">'+ album.album_title + '</a><br>'
	# return HttpResponse(html)
	
	return render(request,'music/index.html',{'all_albums':all_albums})

def detail(request,album_id):
	# try:
	# 	album=Album.objects.get(pk=album_id)
	# except Album.DoesNotExist:
	# 	raise Http404("Album doesNotExist")	
	album=get_object_or_404(Album,pk=album_id)
	return render(request,'music/detail.html',{'album':album})
def favorite(request,album_id):
	album=get_object_or_404(Album,pk=album_id)
	try:
		selected_song=album.song_set.get(pk=)

templates/music/detail.html
<img src='{{album.album_logo}}'>
<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>

<!--  for making list
<ul>
	{% for song in album.song_set.all %}
	<li>{{song.song_title}}-{{ song.file_type}}</li>
	}
	{% endfor %}
</ul> -->

{% if error_message %}
<p><strong>{{error_message}}</strong></p>
{% endif %}

<form action ="{% url 'music:favorite' album.id}" method="post">
	{% csrf_token %}
	{% for song in album.song_set.all %}
	<input type="radio" id="song{{forloop.counter}}" name="song " value="{{song.id}}">
	<label for="song{{forloop.counter}}">
		{{song.song_title}}
		{ % if song.is_favorite %}
		<img src="#" alt="photo of star" />
	</label>
	{% endfor %}
	<input type="submit" name="">
</form>

templates/music/index.html
<!DOCTYPE html>
<html>
<head>
</head>
<body>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{ % static 'music/style.css' %}">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar=toggle">Album</button>
			<a class="nav-brand" href="{% url 'music:index' %}"></a>
		</div>
	</div>
</nav>
{% if all_albums %}
<h3>here is all my albums:</h3><br>
<ul>
	{% for album in all_albums %}
	<!-- <li><a href="/music/{{album.id}}/">{{album.album_title}}</a></li> -->
	<li>
	<a href="{% url 'music:detail' album.id %}"></a></ul></li>
	{% endfor %}
</ul>
{% else %}
<h3>You don't have any albums</h3>
{% endif %}
</body>
</html>